<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>Hi5CentralAppPortal</AssemblyName>
    <RootNamespace>Hi5Central.AppPortal</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.2" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.2" />
  </ItemGroup>

  <PropertyGroup Condition="'$(PublishTrimmed)' == 'true'">
    <WarningsNotAsErrors>$(WarningsNotAsErrors);IL2026;IL2104</WarningsNotAsErrors>
  </PropertyGroup>

  <ItemGroup Condition="'$(PublishTrimmed)' == 'true'">
    <TrimmerRootAssembly Include="Avalonia.Remote.Protocol" />
    <TrimmerRootAssembly Include="Avalonia.DesignerSupport" />
  </ItemGroup>
</Project>